version: '3'
services:
  php-api:
    build:
      context: C:/project/BDD_Creator
    ports:
      - "80:80"
    volumes:
      - ./BDD_Creator:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  react-frontend:
    build:
      context: C:/project/front_bdd_creator
    ports:
      - "3000:3000"
    volumes:
      - ./front_bdd_creator:/app
      # - /app/node_modules
    depends_on:
      - php-api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV="development"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:


